name: .NET Tests & CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List files
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Detect project file
      id: detect_project
      run: echo "PROJECT_FILE=$(find . -name '*.sln' -o -name '*.csproj' | head -n 1)" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore $PROJECT_FILE

    - name: Build project
      run: dotnet build $PROJECT_FILE --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test $PROJECT_FILE --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: TestResults/test_results.trx
