name: .NET Framework 4.7.2 CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Chạy trên Windows để hỗ trợ .NET Framework 4.7.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List files
      run: Get-ChildItem -Recurse  # Liệt kê toàn bộ file để kiểm tra vị trí dự án

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1  # Cài đặt MSBuild để build .NET Framework

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1  # Cài đặt NuGet để restore package

    - name: Restore dependencies
      run: |
        nuget restore KiemThuNangCao.sln
      continue-on-error: false  # Dừng ngay nếu lỗi restore

    - name: Build project
      run: |
        msbuild KiemThuNangCao.sln /p:Configuration=Release
      continue-on-error: false  # Dừng ngay nếu lỗi build

    - name: Run unit tests
      run: |
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
      continue-on-error: true  # Không dừng workflow nếu test thất bại

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: TestResults/test_results.trx
